### ISSUE TITLE
Does the block explorer not work with mysql 8.0.4?

### ISSUE THREAD

**Issue by e-nikolov** [yeasy/docker-compose-files#114]
The base.yaml has this for the block-explorer:
```
mysql-base: # mysql service
    image: mysql:8.0
    restart: always
    expose:
      - "3306"
```

Which since a few days ago started downloading mysql 8.0.4, it used to download 8.0.3 (which used to work).

Now the explorer doesn't start and its logs keep showing this error:

```
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
```
If I fix the mysql version to 8.0.3 it seems to fix the issue.
